'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Otaku_Millionaire_Hot_Seat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5050_lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5050_lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ask_a_Friend_lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ask_a_Friend_lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ask_lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ask_lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AskAFriend() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AskAFriend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AskLifelineResults() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AskLifelineResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AskLifelineSurvay() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AskLifelineSurvay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Battle_Royle_Intro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Battle Royle Intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property contestentIntro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("contestentIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Double_Dip_Lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Double_Dip_Lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DoubleDipFinalAnswer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DoubleDipFinalAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DoubleDipLifelineFirstGuess() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DoubleDipLifelineFirstGuess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DoubleDipSecondChance() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DoubleDipSecondChance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property End_of_Game() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("End of Game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property FinalAndSecondChanceIntro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FinalAndSecondChanceIntro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property FirstAdBreakEnd() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FirstAdBreakEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property FirstandThirdAdBreaksStart() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FirstandThirdAdBreaksStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Level1Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Level1Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Level1QuestionMusic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Level1QuestionMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Level1Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Level1Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property LevelTransitionMusic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("LevelTransitionMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MillionYenWrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MillionYenWrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MilllionYenWin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MilllionYenWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Next_Player_In() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Next Player In", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OneThousandYenWon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OneThousandYenWon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OpeningTheme() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OpeningTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Otaku_Millionaire_Hot_Seat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Otaku_Millionaire_Hot_Seat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pass_lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pass_lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question10_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question10.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question10Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question10Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question10Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question10Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question10Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question10Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11.30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question11Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question11Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12.30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question12Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question12Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13.30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question13Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question13Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question14Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question14Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question15MillionYenFinalAnswer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question15MillionYenFinalAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question15MillionYenQuestion() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question15MillionYenQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question15MillionYenQuestion_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question15MillionYenQuestion.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question15MillionYenQuestion_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question15MillionYenQuestion.30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question6_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question6.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question6Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question6Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question6Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question6Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question6Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question6Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question7_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question7.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question7Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question7Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question7Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question7Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question7Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question7Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question8_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question8.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question8Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question8Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question8Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question8Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question8Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question8Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question9_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question9.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question9Correct() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question9Correct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question9Final() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question9Final", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Question9Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Question9Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Questions14and15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Questions14and15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Questions14and15_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Questions14and15.15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Questions14and15_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Questions14and15.30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Questions14and15FinalAnswer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Questions14and15FinalAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Questions14and15Wrong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Questions14and15Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property QuestionTransitionMusic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("QuestionTransitionMusic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Regular_Ending_Theme() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Regular Ending Theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property RegularWin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("RegularWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SecondAdBreakEnd() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SecondAdBreakEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SecondAdBreaksStart() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SecondAdBreaksStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SecondChanceRules() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SecondChanceRules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property StartGame() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StartGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Three_Beeps() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Three Beeps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trust_the_Computer_lifeline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trust_the_Computer_lifeline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
